name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches_ignore: []

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: ./
          snakefile: workflow/Snakefile
          args: "--lint"

  run-workflow:
    runs-on: ubuntu-latest
    needs:
      - linting
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Test workflow
        uses: snakemake/snakemake-github-action@v1.25.1
        with:
          directory: ./
          snakefile: workflow/Snakefile
          args: "--use-conda --show-failed-logs --cores 4 --conda-cleanup-pkgs cache --all-temp"
